#!/bin/bash
cd ${ZOOG_ROOT}/monitors/linux_dbg/monitor
while [ true ]; do
	./build/xax_port_monitor
	if [ $? == 0 ]; then
		break
	fi
	echo Zzzz... retrying tunnel race
	sleep 1
done

echo Sleeping so you can see any crashy messages.
sleep 100
