ZOOG_ROOT=../../../..

PACKAGE_NAME=inkscape
PIE_NAME=inkscape-pie

PRE_PATCH_SCRIPT=\
	(cd build/source-files/; patch -p2 < ../../presentation.patch)

BUILT_PIE=build/source-files/inkscape-*/src/inkscape

include ../make.in
